export const GET_BARBERS = "GET_BARBERS";
export const GET_BARBERS_SUCCESS = "GET_BARBERS_SUCCESS";
export const GET_BARBERS_ERROR = "GET_BARBERS_ERROR";

export const GET_CLIENTS = "GET_CLIENTS";
export const GET_CLIENTS_SUCCESS = "GET_CLIENTS_SUCCESS";
export const GET_CLIENTS_FAIL = "GET_CLIENTS_FAIL";